[1,"All stages"],
  [2,"Have you identified a sufficient number of qualified enumerators?"],
  [2,"Have you trained the interviewers on the instrument?"],
  [2,"Have you identified a sample size for the pilot?"],
  [2,"Have you secured all approvals / letters of support needed in Egypt?"],
  [2,"Has someone contacted the school leaders in the pilot schools to inform them of planned survey activity?"],
  [2,"Has someone taken care of the logistics (e.g. transportation, meals or per diem for enumerators)?"],
  [2,"Do you have a venue reserved for training the interviewers?"],
[1,"Pre-Pilot"],
  [2,"Do you have a set protocol for identifying teachers for classroom observations?"],
  [2,"Do you have a tool prepared for enumerators to record qualitative observations and notes?"],
  [2,"Have you tested enumerators’ note-taking abilities during the training and provided feedback on content and handwriting?"],
[1,"Content-Focused Pilot"],
  [2,"Is the classroom observation tool you are piloting fully translated into Arabic?"],
  [2,"Is the tool formatted for printing? Make sure there are sufficient margins on all pages for taking notes."],
  [2,"Did you print enough copies of the tool for all enumerators and all M&E Officers accompanying the enumerators to have a copy for each planned observation?"],
  [2,"Have you instructed enumerators to record the start and end time for each class?"],
[1,"Data-Focused Pilot"],
    [3,"Is the name for the pilot form on the database clearly distinguishable from the final survey?"],
    [3,"Have you assigned a form id unique to the pilot? (to avoid confusing pilot data with final data)"],
    [3,"Do all team members who need it have log-on information (if online)?"],
  [2,"If tool is online, are all tablets running the most updated version of their operating system (OS)? (or at a minimum, are they all running exactly the same OS?)"],
  [2,"Are all tablets set to the correct date and time?"],
  [2,"Is the pilot-form downloaded and ready-to-go on all tablets?"],
  [2,"Are all tablets fully charged? Do you have battery packs with you in case any batteries run out?"],
  [2,"Do you have a couple of paper copies of the observation tool, for enumerators to use, and/or as a last resort in case of unsolvable tablet problems?"],
  [2,"Have you built in time to the field plan to make any required revisions to the tool and re-download the revised forms on all tablets?"],
